### ISSUE TITLE
UCD Process for Import Maps

### ISSUE THREAD

**Issue by AshishSanju** [IBM-UrbanCode/IBM-Sterling-B2B-Integrator-UCD#1]
Hello,

Am trying to automate the B2B deployments using UCD. When creating a process to do the deployments am able to execute the check services step but when coming to the other steps like import maps , start -stop B2B am stuck...confused where to give the relative commands, pass the input properties for those steps. 
Can anyone let me how to configure the job within those steps.

PS: Am referring to the plugin document in the repository it is understandable ,but not clear when actually doing hands on.  

![process](https://user-images.githubusercontent.com/19953557/28787106-4792cdf6-75e9-11e7-8456-04d8a3d5e830.PNG)
![result](https://user-images.githubusercontent.com/19953557/28787316-d5d02af0-75e9-11e7-9ca1-4299c684dcf2.PNG)

**Comment by nhmathis** [comment]
Hi,

Except for a few steps, this plugin is structured much differently than our typical plugins. Typically, the plugin.xml and its properties define values and a groovy file to run a full process. However, in most of these steps, such as `Import Maps`, the values are directly used in a command line call. [Here is the code in the plugin.xml.](https://github.com/IBM-UrbanCode/IBM-Sterling-B2B-Integrator-UCD/blob/master/src/main/zip/plugin.xml#L147) You can see here, the values from above (the Sterling Home and Maps Directory) are directly used in the command line call. 

For example, using your screenshot properties for the `Import MAPs` step, the following command would be called...
`C:\SI_5.2.4\install/install/bin/importMAPs.cmd C:\Users\Administrator\Desktop\Maps`

Note: The path separator get converted appropriately by UCD. 

This means, if you can identify the command in question, you can use the Sterling CLI documentation to configure the step appropriately.  

In your particular example, I can see two issues. 

1) The `install` folder is specified twice. Once by the input value and a second by the plugin.xml. You can either remove it from the plugin.xml and recompile (not suggested) or simply remove it from your plugin step configuration (suggested). 
2) Undocumented here, you've specified some invalid javascript for the Precondition in both your `Import MAPs` and `Stop B2Bi` steps. Preconditions should not be necessary.

If there are other arguments you need to specify for some of the Sterling's cli calls, you'll either need to modify the plugin and add these properties the plugin xml (feel free to submit a pull request if you do!) or use the Shell step.

**Comment by AshishSanju** [comment]
Hello @nhmathis ,

Thanks for the response, I will try to change the home directory path and run the process , but we have couple of SI servers which are having the same paths and cannot  change the paths for all the servers, I prefer changing the plugin.xml , may i know what type of build  is necessary to compile the modified code (i.e Maven ,gradle ...)  .

**Comment by nhmathis** [comment]
Modifying the plugin.xml is not recommended. If you did, you would need duplicated steps or plugins in your UCD sever. This can make any future configuration very confusing.

Instead, all SI installations folders should have the following structure `<SI_INSTALL_DIR>/install/bin/COMMAND`. You just need to supply the `SI_INSTALL_DIR` part as the second half of the structure is taken care of by the plugin. Fortunately, through the use of properties, you can make the SI_INSTALL_DIR value dynamic. For example, based on the environment or agent you run it against, you can specify a property that will be resolved dynamically. [More information on properties can be found here.](https://www.ibm.com/support/knowledgecenter/en/SS4GSP_6.1.2/com.ibm.udeploy.reference.doc/topics/ud_properties.html)

To answer your original question, this plugin can be built using `gradle`.

**Comment by AshishSanju** [comment]
I implemented the changes you've suggested and it's working good now...!!

Thank you @nhmathis

**Comment by nhmathis** [comment]
Glad to help!

**Comment by AshishSanju** [comment]
Hello @nhmathis ,

Is it possible to create a component level process for SI where i'll be getting the maps from a VCS , then run this component in an Environment by creating a application level process..?
If am creating a generic process and running it at an application-level by selecting environment it is happening.
Working method
![app-componentlevel process](https://user-images.githubusercontent.com/19953557/29421196-4d73f73e-8342-11e7-89b4-78820ecaa3c2.PNG)

unsucessful method
![versioned](https://user-images.githubusercontent.com/19953557/29421362-ddad7d70-8342-11e7-92ea-1c28e8adeee6.PNG)

**Comment by nhmathis** [comment]
@AshishSanju, I'm answering this question in Issue #2.
