### ISSUE TITLE
Retrieve Artifacts from VCS

### ISSUE THREAD

**Issue by nhmathis** [IBM-UrbanCode/IBM-Sterling-B2B-Integrator-UCD#2]
Original Question asked in [#1-323114211](https://github.com/IBM-UrbanCode/IBM-Sterling-B2B-Integrator-UCD/issues/1#issuecomment-323114211)

Is it possible to create a component level process for SI where i'll be getting the maps from a VCS , then run this component in an Environment by creating a application level process..?
If am creating a generic process and running it at an application-level by selecting environment it is happening.

**Comment by nhmathis** [comment]
I recently wrote a blog post about importing artifacts into UCD when there isn't a build tool or source config plugin to utilize. 

[Creating Versions without a Build or CI Tool](https://developer.ibm.com/urbancode/docs/creating-versions-without-a-build-or-ci-tool/)

It's in the context of DataPower however, the topics still apply to many other services. It outlines how to run the import steps in a component process, and then immediately kick off your following application process. There is likely a small configuration part of the component process you are missing.

Give it a read and let me know if there is any confusion or it doesn't answer your questions.

**Comment by AshishSanju** [comment]
@nhmathis Okay Sure..!!
